# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180710_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=128)),
                ('items', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
